import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '../globals.css'
import HomeNavbar from '@/components/HomeNavbar'

const inter = Poppins({
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'IVE 아이브 | DIVE INTO IVE!',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <HomeNavbar />
                {children}
            </body>
        </html>
    )
}
